/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
//import DAO.DAO_PROJECT;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
//import model.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import java.util.Date;
import model.TicketModelClass;
  

public class TicketButtonForm extends javax.swing.JFrame {
      TicketButtonForm myView;
      Connection conn=null;
  Statement stm=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
// DAO_PROJECT daoReg=new DAO_PROJECT();

          TicketModelClass myModel;
//    DefaultTableModel dtm=null;

    /**
     * Creates new form TicketButtonForm
     */
    public TicketButtonForm() {
        initComponents();
        setSize(1920,1200);
        this.setLocationRelativeTo(null);
    }

    
    public TicketModelClass getData() {
    int arrivalTime = Integer.parseInt(txtArrivalTime.getText());
    int departureTime = Integer.parseInt(txtDeparture.getText());
    
    int phoneNumber = Integer.parseInt(txtPhoneNumber.getText());
           String seatNumber = (String) txtSeatNumber.getSelectedItem();
           String source = (String) txtSource.getText();
    String destination = (String) txtDestination.getText();
     String train = (String) txtTrainno.getSelectedItem();
    
   Date datee = new Date();
    int ticketPrice = Integer.parseInt(txtTicketprice.getText());
    int jbutton1 = Integer.parseInt(jButton1.getText());
    int jbutton2 = Integer.parseInt(jButton2.getText());
       int jbutton3 = Integer.parseInt(jButton3.getText());
       int jbutton4 = Integer.parseInt(jButton4.getText());
       int jbutton5 = Integer.parseInt(jButton5.getText());
   
   
    myModel = new TicketModelClass(arrivalTime, departureTime, phoneNumber, seatNumber, source, destination, train, datee, ticketPrice, jbutton1, jbutton2, jbutton3, jbutton4, jbutton5);
    return myModel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        lblClassC = new javax.swing.JLabel();
        lblClassB = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblClassA = new javax.swing.JLabel();
        lblSeat = new javax.swing.JLabel();
        txtSeatNumber = new javax.swing.JComboBox<>();
        lblChooseClass = new javax.swing.JLabel();
        txtTrainno = new javax.swing.JComboBox<>();
        lblTrainNumber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTicketprice = new javax.swing.JTextField();
        lblTicketPrice = new javax.swing.JLabel();
        txtArrivalTime = new javax.swing.JTextField();
        lblArrivalTime = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        lblSourceDestination = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnGenerateTicket = new javax.swing.JButton();
        txtDate = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDeparture = new javax.swing.JTextField();
        lblDepartureTime = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTrain = new javax.swing.JLabel();
        btnTrain = new javax.swing.JButton();
        lblBookings = new javax.swing.JLabel();
        btnBooking = new javax.swing.JButton();
        lblTicekts = new javax.swing.JLabel();
        btnTicekts = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTrains = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setLayout(null);

        jButton24.setBackground(new java.awt.Color(102, 255, 102));
        jButton24.setText("B6");
        jPanel1.add(jButton24);
        jButton24.setBounds(1750, 870, 72, 30);

        jButton23.setBackground(new java.awt.Color(102, 255, 102));
        jButton23.setText("B5");
        jPanel1.add(jButton23);
        jButton23.setBounds(1680, 870, 72, 30);

        jButton22.setBackground(new java.awt.Color(102, 255, 102));
        jButton22.setText("D4");
        jPanel1.add(jButton22);
        jButton22.setBounds(1750, 820, 72, 30);

        jButton21.setBackground(new java.awt.Color(102, 255, 102));
        jButton21.setText("D3");
        jPanel1.add(jButton21);
        jButton21.setBounds(1680, 820, 72, 30);

        jButton20.setBackground(new java.awt.Color(102, 255, 102));
        jButton20.setText("D2");
        jPanel1.add(jButton20);
        jButton20.setBounds(1750, 760, 72, 30);

        jButton19.setBackground(new java.awt.Color(102, 255, 102));
        jButton19.setText("D1");
        jPanel1.add(jButton19);
        jButton19.setBounds(1680, 760, 72, 30);

        jButton18.setBackground(new java.awt.Color(102, 255, 102));
        jButton18.setText("C6");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(1480, 870, 72, 30);

        jButton17.setBackground(new java.awt.Color(102, 255, 102));
        jButton17.setText("C5");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(1410, 870, 72, 30);

        jButton16.setBackground(new java.awt.Color(102, 255, 102));
        jButton16.setText("C4");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(1480, 820, 70, 30);

        jButton15.setBackground(new java.awt.Color(102, 255, 102));
        jButton15.setText("C3");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(1410, 820, 70, 30);

        jButton14.setBackground(new java.awt.Color(102, 255, 102));
        jButton14.setText("C2");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(1480, 760, 70, 30);

        jButton25.setBackground(new java.awt.Color(102, 255, 102));
        jButton25.setText("E2");
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton25MouseClicked(evt);
            }
        });
        jPanel1.add(jButton25);
        jButton25.setBounds(1490, 970, 70, 30);

        jButton13.setBackground(new java.awt.Color(102, 255, 102));
        jButton13.setText("C1");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(1410, 760, 70, 30);

        lblClassC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblClassC.setText("Class C");
        jPanel1.add(lblClassC);
        lblClassC.setBounds(1580, 940, 70, 20);

        lblClassB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblClassB.setText("Class B");
        jPanel1.add(lblClassB);
        lblClassB.setBounds(1580, 730, 80, 30);

        jButton12.setBackground(new java.awt.Color(102, 255, 102));
        jButton12.setText("B6");
        jPanel1.add(jButton12);
        jButton12.setBounds(1752, 660, 72, 30);

        jButton11.setBackground(new java.awt.Color(102, 255, 102));
        jButton11.setText("B4");
        jPanel1.add(jButton11);
        jButton11.setBounds(1752, 610, 72, 30);

        jButton10.setBackground(new java.awt.Color(102, 255, 102));
        jButton10.setText("B2");
        jPanel1.add(jButton10);
        jButton10.setBounds(1750, 550, 72, 30);

        jButton9.setBackground(new java.awt.Color(102, 255, 102));
        jButton9.setText("B5");
        jPanel1.add(jButton9);
        jButton9.setBounds(1680, 660, 72, 30);

        jButton8.setBackground(new java.awt.Color(102, 255, 102));
        jButton8.setText("B3");
        jPanel1.add(jButton8);
        jButton8.setBounds(1680, 610, 72, 30);

        jButton7.setBackground(new java.awt.Color(102, 255, 102));
        jButton7.setText("B1");
        jPanel1.add(jButton7);
        jButton7.setBounds(1680, 550, 72, 30);

        jButton6.setBackground(new java.awt.Color(102, 255, 102));
        jButton6.setText("A6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(1480, 660, 72, 30);

        jButton5.setBackground(new java.awt.Color(102, 255, 102));
        jButton5.setText("A5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(1410, 660, 72, 30);

        jButton26.setBackground(new java.awt.Color(102, 255, 102));
        jButton26.setText("E5");
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton26MouseClicked(evt);
            }
        });
        jPanel1.add(jButton26);
        jButton26.setBounds(1420, 1070, 70, 30);

        jButton27.setBackground(new java.awt.Color(102, 255, 102));
        jButton27.setText("E1");
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton27MouseClicked(evt);
            }
        });
        jPanel1.add(jButton27);
        jButton27.setBounds(1420, 970, 70, 30);

        jButton28.setBackground(new java.awt.Color(102, 255, 102));
        jButton28.setText("E3");
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton28MouseClicked(evt);
            }
        });
        jPanel1.add(jButton28);
        jButton28.setBounds(1420, 1020, 70, 30);

        jButton29.setBackground(new java.awt.Color(102, 255, 102));
        jButton29.setText("E6");
        jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton29MouseClicked(evt);
            }
        });
        jPanel1.add(jButton29);
        jButton29.setBounds(1490, 1070, 70, 30);

        jButton30.setBackground(new java.awt.Color(102, 255, 102));
        jButton30.setText("F2");
        jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton30MouseClicked(evt);
            }
        });
        jPanel1.add(jButton30);
        jButton30.setBounds(1750, 970, 70, 30);

        jButton31.setBackground(new java.awt.Color(102, 255, 102));
        jButton31.setText("E4");
        jButton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton31MouseClicked(evt);
            }
        });
        jPanel1.add(jButton31);
        jButton31.setBounds(1490, 1020, 70, 30);

        jButton32.setBackground(new java.awt.Color(102, 255, 102));
        jButton32.setText("F3");
        jButton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton32MouseClicked(evt);
            }
        });
        jPanel1.add(jButton32);
        jButton32.setBounds(1680, 1020, 70, 30);

        jButton33.setBackground(new java.awt.Color(102, 255, 102));
        jButton33.setText("F5");
        jButton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton33MouseClicked(evt);
            }
        });
        jPanel1.add(jButton33);
        jButton33.setBounds(1680, 1070, 70, 30);

        jButton34.setBackground(new java.awt.Color(102, 255, 102));
        jButton34.setText("F6");
        jButton34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton34MouseClicked(evt);
            }
        });
        jPanel1.add(jButton34);
        jButton34.setBounds(1750, 1070, 70, 30);

        jButton35.setBackground(new java.awt.Color(102, 255, 102));
        jButton35.setText("F1");
        jButton35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton35MouseClicked(evt);
            }
        });
        jPanel1.add(jButton35);
        jButton35.setBounds(1680, 970, 70, 30);

        jButton36.setBackground(new java.awt.Color(102, 255, 102));
        jButton36.setText("F4");
        jButton36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton36MouseClicked(evt);
            }
        });
        jPanel1.add(jButton36);
        jButton36.setBounds(1750, 1020, 70, 30);

        jButton4.setBackground(new java.awt.Color(102, 255, 102));
        jButton4.setText("A4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1480, 610, 70, 30);

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setText("A3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1410, 610, 70, 30);

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setText("A2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1480, 550, 70, 30);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setText("  A1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1410, 550, 70, 30);

        lblClassA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblClassA.setText("Class A");
        jPanel1.add(lblClassA);
        lblClassA.setBounds(1580, 520, 80, 20);

        lblSeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seatrec.png"))); // NOI18N
        jPanel1.add(lblSeat);
        lblSeat.setBounds(1370, 480, 500, 640);

        txtSeatNumber.setBackground(new java.awt.Color(195, 228, 232));
        txtSeatNumber.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtSeatNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Class", "Class A", "Class B", "Class C", " " }));
        txtSeatNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSeatNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSeatNumberMouseClicked(evt);
            }
        });
        jPanel1.add(txtSeatNumber);
        txtSeatNumber.setBounds(1430, 300, 230, 50);

        lblChooseClass.setFont(new java.awt.Font("Georgia", 0, 27)); // NOI18N
        lblChooseClass.setText("Choose Class");
        jPanel1.add(lblChooseClass);
        lblChooseClass.setBounds(1430, 260, 180, 31);

        txtTrainno.setBackground(new java.awt.Color(195, 228, 232));
        txtTrainno.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtTrainno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Train", "Janakpur Dham Train", "DhaniGadi Train", "SoSo Train" }));
        txtTrainno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTrainno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrainnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTrainno);
        txtTrainno.setBounds(1430, 160, 230, 50);

        lblTrainNumber.setFont(new java.awt.Font("Georgia", 0, 27)); // NOI18N
        lblTrainNumber.setText("Train");
        jPanel1.add(lblTrainNumber);
        lblTrainNumber.setBounds(1430, 110, 70, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 16.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1370, 50, 482, 357);

        txtTicketprice.setBackground(new java.awt.Color(195, 228, 232));
        txtTicketprice.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        txtTicketprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtTicketprice);
        txtTicketprice.setBounds(980, 510, 230, 50);

        lblTicketPrice.setFont(new java.awt.Font("Georgia", 0, 27)); // NOI18N
        lblTicketPrice.setText("Ticket Price");
        jPanel1.add(lblTicketPrice);
        lblTicketPrice.setBounds(980, 470, 140, 30);

        txtArrivalTime.setBackground(new java.awt.Color(195, 228, 232));
        txtArrivalTime.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        txtArrivalTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtArrivalTime);
        txtArrivalTime.setBounds(980, 360, 230, 50);

        lblArrivalTime.setFont(new java.awt.Font("Georgia", 0, 27)); // NOI18N
        lblArrivalTime.setText("Arrival Time");
        jPanel1.add(lblArrivalTime);
        lblArrivalTime.setBounds(980, 320, 160, 31);

        txtDestination.setBackground(new java.awt.Color(195, 228, 232));
        txtDestination.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        txtDestination.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtDestination);
        txtDestination.setBounds(1100, 200, 110, 50);

        txtSource.setBackground(new java.awt.Color(195, 228, 232));
        txtSource.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        txtSource.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSourceActionPerformed(evt);
            }
        });
        jPanel1.add(txtSource);
        txtSource.setBounds(980, 200, 110, 50);

        lblSourceDestination.setFont(new java.awt.Font("Georgia", 0, 27)); // NOI18N
        lblSourceDestination.setText("Source Destination");
        jPanel1.add(lblSourceDestination);
        lblSourceDestination.setBounds(980, 160, 240, 31);

        btnReset.setBackground(new java.awt.Color(5, 77, 170));
        btnReset.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        jPanel1.add(btnReset);
        btnReset.setBounds(1010, 610, 130, 50);

        btnUpdate.setBackground(new java.awt.Color(5, 77, 170));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(820, 610, 140, 50);

        btnGenerateTicket.setBackground(new java.awt.Color(5, 77, 170));
        btnGenerateTicket.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        btnGenerateTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateTicket.setText("GENERATE TICKET");
        btnGenerateTicket.setBorder(null);
        btnGenerateTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateTicketMouseClicked(evt);
            }
        });
        btnGenerateTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTicketActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerateTicket);
        btnGenerateTicket.setBounds(560, 610, 200, 50);

        txtDate.setBackground(new java.awt.Color(195, 228, 232));
        txtDate.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        txtDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtDate);
        txtDate.setBounds(540, 510, 230, 50);

        lblDate.setFont(new java.awt.Font("Georgia", 0, 27)); // NOI18N
        lblDate.setText("Date");
        jPanel1.add(lblDate);
        lblDate.setBounds(540, 470, 70, 30);

        txtDeparture.setBackground(new java.awt.Color(195, 228, 232));
        txtDeparture.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        txtDeparture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartureActionPerformed(evt);
            }
        });
        jPanel1.add(txtDeparture);
        txtDeparture.setBounds(540, 370, 230, 50);

        lblDepartureTime.setFont(new java.awt.Font("Georgia", 0, 27)); // NOI18N
        lblDepartureTime.setText("Departure Time");
        jPanel1.add(lblDepartureTime);
        lblDepartureTime.setBounds(540, 330, 200, 31);

        txtPhoneNumber.setBackground(new java.awt.Color(195, 228, 232));
        txtPhoneNumber.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPhoneNumber);
        txtPhoneNumber.setBounds(540, 210, 230, 50);

        lblPhoneNumber.setFont(new java.awt.Font("Georgia", 0, 27)); // NOI18N
        lblPhoneNumber.setText("Phone Number");
        jPanel1.add(lblPhoneNumber);
        lblPhoneNumber.setBounds(540, 170, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 15.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 80, 820, 630);

        lblTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Frame.png"))); // NOI18N
        jPanel1.add(lblTrain);
        lblTrain.setBounds(60, 40, 260, 140);

        btnTrain.setBackground(new java.awt.Color(42, 134, 251));
        btnTrain.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnTrain.setForeground(new java.awt.Color(5, 51, 111));
        btnTrain.setText("TRAINS");
        btnTrain.setBorder(null);
        btnTrain.setBorderPainted(false);
        btnTrain.setContentAreaFilled(false);
        btnTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrainMouseExited(evt);
            }
        });
        btnTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrainActionPerformed(evt);
            }
        });
        jPanel1.add(btnTrain);
        btnTrain.setBounds(130, 460, 130, 60);

        lblBookings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tabler_brand-booking (1).png"))); // NOI18N
        jPanel1.add(lblBookings);
        lblBookings.setBounds(40, 620, 80, 80);

        btnBooking.setBackground(new java.awt.Color(42, 134, 251));
        btnBooking.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(5, 51, 100));
        btnBooking.setText("BOOKING");
        btnBooking.setBorder(null);
        btnBooking.setBorderPainted(false);
        btnBooking.setContentAreaFilled(false);
        btnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingMouseExited(evt);
            }
        });
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });
        jPanel1.add(btnBooking);
        btnBooking.setBounds(130, 630, 160, 60);

        lblTicekts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ticketsGreen.png"))); // NOI18N
        jPanel1.add(lblTicekts);
        lblTicekts.setBounds(45, 790, 80, 80);

        btnTicekts.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnTicekts.setForeground(new java.awt.Color(5, 51, 100));
        btnTicekts.setText("TICKETS");
        btnTicekts.setBorder(null);
        btnTicekts.setBorderPainted(false);
        btnTicekts.setContentAreaFilled(false);
        btnTicekts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTicektsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTicektsMouseExited(evt);
            }
        });
        btnTicekts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicektsActionPerformed(evt);
            }
        });
        jPanel1.add(btnTicekts);
        btnTicekts.setBounds(140, 810, 140, 50);

        btnExit.setBackground(new java.awt.Color(42, 134, 251));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/material-symbols_logout-rounded.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(130, 960, 120, 90);

        lblTrains.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trainLabel.png"))); // NOI18N
        jPanel1.add(lblTrains);
        lblTrains.setBounds(40, 450, 80, 80);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/c.png"))); // NOI18N
        btnUser.setBorder(null);
        btnUser.setBorderPainted(false);
        btnUser.setContentAreaFilled(false);
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
        });
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnUser);
        btnUser.setBounds(130, 250, 130, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BlueGreen.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 0, 1550, 1120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTicektsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicektsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTicektsActionPerformed

    private void btnTicektsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicektsMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTicektsMouseExited

    private void btnTicektsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicektsMouseEntered
        // TODO add your handling code here:
         Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnTicekts.setCursor(cursor);
    }//GEN-LAST:event_btnTicektsMouseEntered

    private void btnTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainMouseClicked
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_btnTrainMouseClicked

    private void btnTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrainActionPerformed
        TrainButtonForm tbForm=new TrainButtonForm();
        tbForm.setVisible(true);     
        this.dispose();
        
    }//GEN-LAST:event_btnTrainActionPerformed

    private void btnTrainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainMouseEntered
        // TODO add your handling code here:
         Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnTrain.setCursor(cursor);
    }//GEN-LAST:event_btnTrainMouseEntered

    private void btnTrainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainMouseExited
        // TODO add your handling code here:
          btnTrain.setBackground(new java.awt.Color(42, 134, 251));
        btnTrain.setContentAreaFilled(false);
    }//GEN-LAST:event_btnTrainMouseExited

    private void btnBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseExited
        // TODO add your handling code here:
          btnBooking.setBackground(new java.awt.Color(42, 134, 251));
        btnBooking.setContentAreaFilled(false);
    }//GEN-LAST:event_btnBookingMouseExited

    private void btnBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseEntered
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnBooking.setCursor(cursor);
    }//GEN-LAST:event_btnBookingMouseEntered

    private void btnBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBookingMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        BookingButtonForm corm=new BookingButtonForm();
        corm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        dashboard db=new dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
         Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnUser.setCursor(cursor);
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
         Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnExit.setCursor(cursor);
    }//GEN-LAST:event_btnExitMouseEntered

    private void txtDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartureActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnGenerateTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateTicketMouseClicked

    }//GEN-LAST:event_btnGenerateTicketMouseClicked

    private void btnGenerateTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateTicketActionPerformed
//
//        DAO_PROJECT daoReg = new DAO_PROJECT();

//        if (daoReg.checkSignUpData(myModel)) {
//            JOptionPane.showMessageDialog(this, "Successfully registered", "Ticket", JOptionPane.INFORMATION_MESSAGE);
//        } else {
//            JOptionPane.showMessageDialog(this, "Error while inserting data", "Ticket", JOptionPane.ERROR_MESSAGE);
//        }

        //    txtArea.setText("*************************************\n");
        //    txtArea.setText(txtArea.getText()+"**\n");

        //    Date obj=new Date();
        //    String date=obj.toString();
        //    txtArea.setText("                              TICKET                                        \n\n");
        //    txtArea.setText(txtArea.getText()+"\n"+date+"\n\n\n");
        //    txtArea.setText(txtArea.getText()+"Departure Time:  "+txtDeparture.getText());
        //    txtArea.setText(txtArea.getText()+"                   Arrival Time:  "+txtArrivalTime.getText()+"\n\n\n");
        //
        ////    txtArea.setText(txtArea.getText()+"Passenger Name:  "+txpassengername.getText()+"\n");
        ////    txtArea.setText(txtArea.getText()+"Train Number:  "+txtTrainno.getText()+"\n");
        //    txtArea.setText(txtArea.getText()+"To The Destination:  "+txtDate.getText()+"\n");
        ////    txtArea.setText(txtArea.getText()+"Your Seat Number is:  "+txtSeatno.getText()+"\n");
        //    txtArea.setText(txtArea.getText()+"Ticket Price:  "+txtTicketprice.getText()+"\n");
        //

    }//GEN-LAST:event_btnGenerateTicketActionPerformed

    private void txtSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceActionPerformed

    }//GEN-LAST:event_txtSourceActionPerformed

    private void txtTrainnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrainnoActionPerformed
        // TODO add your handling code here:
        txtTrainno.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedTrain = (String) txtTrainno.getSelectedItem();
                // Call a method to retrieve the corresponding source and destination based on the selected train
                String[] sourceAndDestination = getSourceAndDestination(selectedTrain);
                //

                txtSource.setText(sourceAndDestination[0]);
                txtDestination.setText(sourceAndDestination[1]);
                //
                //

            }
            //
            //
            //    // Method to retrieve the source and destination based on the selected train
            private String[] getSourceAndDestination(String selectedTrain) {

                String[] sourceAndDestination = new String[2];

                switch (selectedTrain) {
                    case "Janakpur Dham Train" -> {
                        sourceAndDestination[0] = "  Janakpur";
                        sourceAndDestination[1] = "  Jayanagar";
                    }
                    case "DhaniGadi Train" -> {
                        sourceAndDestination[0] = "  Dang";
                        sourceAndDestination[1] = "  Sarlahi";
                    }
                    case "SoSo Train" -> {
                        sourceAndDestination[0] = "  Sunsari";
                        sourceAndDestination[1] = "  Saptari";
                    }
                    default -> {
                    }
                }

                // Add more conditions or retrieve the source and destination dynamically from a database

                return sourceAndDestination;

            }

        }  );

    }//GEN-LAST:event_txtTrainnoActionPerformed

    private void txtSeatNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSeatNumberMouseClicked

    }//GEN-LAST:event_txtSeatNumberMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        String seatNumber = jButton1.getText();
        String confirmationDo = "Do you want to select the seat" + seatNumber;
        int confirmation = JOptionPane.showConfirmDialog(rootPane, confirmationDo, "Seat Selection", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            // Seat is selected, perform necessary actions
            jButton1.setBackground(Color.RED);

            //   selectedSeats.add(seatNumber);
            String confirmationMessage = "Seat " + seatNumber + " has been selected.";
            JOptionPane.showMessageDialog(rootPane, confirmationMessage, "Seat Selected", JOptionPane.INFORMATION_MESSAGE);

            // ...
        } else {
            // Seat selection canceled, handle accordingly
            // ...
            jButton1.setBackground(Color.green);
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String seatNumber = jButton2.getText(); // Get the seat number from the button text
        String confirmation = "Do you want to select the seat " + seatNumber;
        int confirmation1 = JOptionPane.showConfirmDialog(rootPane, confirmation, "Seat Selection", JOptionPane.YES_NO_OPTION);
        if (confirmation1 == JOptionPane.YES_OPTION) {
            // Seat is selected, perform necessary actions
            jButton2.setBackground(Color.RED);
            //     selectedSeats.add(seatNumber);

            String confirmationMessage1 = "Seat " + seatNumber+ " has been selected.";
            JOptionPane.showMessageDialog(rootPane, confirmationMessage1, "Seat Selected", JOptionPane.INFORMATION_MESSAGE);

            // ...
        } else {
            // Seat selection canceled, handle accordingly

            jButton2.setBackground(Color.green);
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String seatNumber = jButton3.getText(); // Get the seat number from the button text
        String confirmation3 = "Do you want to select the seat " + seatNumber;
        int confirmation4= JOptionPane.showConfirmDialog(rootPane, confirmation3, "Seat Selection", JOptionPane.YES_NO_OPTION);
        if (confirmation4 == JOptionPane.YES_OPTION) {
            // Seat is selected, perform necessary actions
            jButton3.setBackground(Color.RED);
            //    selectedSeats.add(seatNumber);

            String confirmationMessage1 = "Seat " + seatNumber + " has been selected.";
            JOptionPane.showMessageDialog(rootPane, confirmationMessage1, "Seat Selected", JOptionPane.INFORMATION_MESSAGE);

            // ...
        } else {
            // Seat selection canceled, handle accordingly

            jButton3.setBackground(Color.green);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String seatNumber= jButton4.getText(); // Get the seat number from the button text
        String confirmation4 = "Do you want to select the seat " + seatNumber;
        int confirmation5 = JOptionPane.showConfirmDialog(rootPane, confirmation4, "Seat Selection", JOptionPane.YES_NO_OPTION);
        if (confirmation5 == JOptionPane.YES_OPTION) {
            // Seat is selected, perform necessary actions
            jButton4.setBackground(Color.RED);
            //     selectedSeats.add(seatNumber);
            String confirmationMessage1 = "Seat " + seatNumber+ " has been selected.";
            JOptionPane.showMessageDialog(rootPane, confirmationMessage1, "Seat Selected", JOptionPane.INFORMATION_MESSAGE);

            // ...
        } else {
            // Seat selection canceled, handle accordingly

            jButton4.setBackground(Color.green);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String seatNumber = jButton5.getText(); // Get the seat number from the button text
        String confirmation5 = "Do you want to select the seat " + seatNumber;
        int confirmation6 = JOptionPane.showConfirmDialog(rootPane, confirmation5, "Seat Selection", JOptionPane.YES_NO_OPTION);
        if (confirmation6 == JOptionPane.YES_OPTION) {
            // Seat is selected, perform necessary actions
            jButton5.setBackground(Color.RED);
            //     selectedSeats.add(seatNumber);
            String confirmationMessage1 = "Seat " + seatNumber + " has been selected.";
            JOptionPane.showMessageDialog(rootPane, confirmationMessage1, "Seat Selected", JOptionPane.INFORMATION_MESSAGE);

            // ...
        } else {
            // Seat selection canceled, handle accordingly

            jButton5.setBackground(Color.green);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //       String seatNumber1 = jButton6.getText(); // Get the seat number from the button text
        //        String confirmation = "Do you want to select the seat " + seatNumber1;
        //         int confirmation1 = JOptionPane.showConfirmDialog(rootPane, confirmation, "Seat Selection", JOptionPane.YES_NO_OPTION);
        //if (confirmation1 == JOptionPane.YES_OPTION) {
            //    // Seat is selected, perform necessary actions
            //    jButton6.setBackground(Color.RED);
            //
            //    String confirmationMessage1 = "Seat " + seatNumber1 + " has been selected.";
            //        JOptionPane.showMessageDialog(rootPane, confirmationMessage1, "Seat Selected", JOptionPane.INFORMATION_MESSAGE);
            //
            //
            //
            //    // ...
            //} else {
            //    // Seat selection canceled, handle accordingly
            //
            //    jButton6.setBackground(Color.green);
            //}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25MouseClicked

    private void jButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26MouseClicked

    private void jButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27MouseClicked

    private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28MouseClicked

    private void jButton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29MouseClicked

    private void jButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30MouseClicked

    private void jButton31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31MouseClicked

    private void jButton32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton32MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32MouseClicked

    private void jButton33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33MouseClicked

    private void jButton34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34MouseClicked

    private void jButton35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35MouseClicked

    private void jButton36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketButtonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerateTicket;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTicekts;
    private javax.swing.JButton btnTrain;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArrivalTime;
    private javax.swing.JLabel lblBookings;
    private javax.swing.JLabel lblChooseClass;
    private javax.swing.JLabel lblClassA;
    private javax.swing.JLabel lblClassB;
    private javax.swing.JLabel lblClassC;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDepartureTime;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSeat;
    private javax.swing.JLabel lblSourceDestination;
    private javax.swing.JLabel lblTicekts;
    private javax.swing.JLabel lblTicketPrice;
    private javax.swing.JLabel lblTrain;
    private javax.swing.JLabel lblTrainNumber;
    private javax.swing.JLabel lblTrains;
    private javax.swing.JTextField txtArrivalTime;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDeparture;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JComboBox<String> txtSeatNumber;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTicketprice;
    private javax.swing.JComboBox<String> txtTrainno;
    // End of variables declaration//GEN-END:variables

    public void showMessageBox(String registered_succesfully) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
