/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Connection_Database.MyConnection;
import controller.ControllerProj;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


import view.*;


   
    
  

public class TicketButtonForm extends javax.swing.JFrame {
       TicketModelClass myModel;
       TicketButtonForm myView;
       Connection conn=null;
    Statement stm=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    DefaultTableModel dtm=null;
       



    /**
     * Creates new form TicketButtonForm
     */
    public TicketButtonForm() {
        initComponents();
        setSize(1920,1200);
        this.setLocationRelativeTo(null);
    }   
    
   public TicketModelClass getData() {
    int arrivalTime = Integer.parseInt(txtArrivalTime.getText());
    int departureTime = Integer.parseInt(txtDeparture.getText());
    int passengerId = Integer.parseInt(txtPassengerId.getText());
    String passengerName = txpassengername.getText();
    int phoneNumber = Integer.parseInt(txtPhoneNumber.getText());
    int seatNumber = Integer.parseInt(txtSeatno.getText());
    String sourceDestination = txtSourceDestination.getText();
    int ticketPrice = Integer.parseInt(txtTicketprice.getText());
    int trainNumber = Integer.parseInt(txtTrainno.getText());

    myModel = new TicketModelClass(arrivalTime, departureTime, passengerId, passengerName, phoneNumber, seatNumber, sourceDestination, ticketPrice, trainNumber);
    return myModel;
    
  

}



    public void showMessageBox(String msg){
        JOptionPane.showMessageDialog(this, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblPassengerName = new javax.swing.JLabel();
        txpassengername = new javax.swing.JTextField();
        lblPassengerId = new javax.swing.JLabel();
        txtPassengerId = new javax.swing.JTextField();
        lblTrainNumber = new javax.swing.JLabel();
        txtTrainno = new javax.swing.JTextField();
        lblSourceDestination = new javax.swing.JLabel();
        lblDepartureTime = new javax.swing.JLabel();
        lblArrivalTime = new javax.swing.JLabel();
        lblTicketPrice = new javax.swing.JLabel();
        btnGenerateTicket = new javax.swing.JButton();
        txtSeatno = new javax.swing.JTextField();
        lblSeatNumber = new javax.swing.JLabel();
        txtSourceDestination = new javax.swing.JTextField();
        txtTicketprice = new javax.swing.JTextField();
        txtArrivalTime = new javax.swing.JTextField();
        txtDeparture = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        lblTrain = new javax.swing.JLabel();
        btnTrain = new javax.swing.JButton();
        lblBookings = new javax.swing.JLabel();
        btnBooking = new javax.swing.JButton();
        lblTicekts = new javax.swing.JLabel();
        btnTicekts = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTrains = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        lblGreenBlueFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(195, 228, 232));
        jPanel2.setLayout(null);

        lblPhoneNumber.setFont(new java.awt.Font("Georgia", 0, 25)); // NOI18N
        lblPhoneNumber.setText("Phone Number");
        jPanel2.add(lblPhoneNumber);
        lblPhoneNumber.setBounds(40, 310, 180, 30);
        jPanel2.add(txtPhoneNumber);
        txtPhoneNumber.setBounds(260, 310, 200, 40);

        lblPassengerName.setFont(new java.awt.Font("Georgia", 0, 25)); // NOI18N
        lblPassengerName.setText("Passenger Name");
        jPanel2.add(lblPassengerName);
        lblPassengerName.setBounds(30, 80, 200, 50);

        txpassengername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpassengernameActionPerformed(evt);
            }
        });
        jPanel2.add(txpassengername);
        txpassengername.setBounds(260, 90, 200, 40);

        lblPassengerId.setFont(new java.awt.Font("Georgia", 0, 25)); // NOI18N
        lblPassengerId.setText("PassengerID");
        jPanel2.add(lblPassengerId);
        lblPassengerId.setBounds(50, 190, 170, 29);
        jPanel2.add(txtPassengerId);
        txtPassengerId.setBounds(260, 190, 200, 40);

        lblTrainNumber.setFont(new java.awt.Font("Georgia", 0, 25)); // NOI18N
        lblTrainNumber.setText("Train Number");
        jPanel2.add(lblTrainNumber);
        lblTrainNumber.setBounds(50, 430, 170, 29);
        jPanel2.add(txtTrainno);
        txtTrainno.setBounds(260, 430, 200, 40);

        lblSourceDestination.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lblSourceDestination.setText("Source Destination");
        jPanel2.add(lblSourceDestination);
        lblSourceDestination.setBounds(30, 550, 220, 34);

        lblDepartureTime.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lblDepartureTime.setText("Departure Time");
        jPanel2.add(lblDepartureTime);
        lblDepartureTime.setBounds(520, 190, 180, 34);

        lblArrivalTime.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lblArrivalTime.setText("Arrival Time");
        jPanel2.add(lblArrivalTime);
        lblArrivalTime.setBounds(540, 310, 140, 34);

        lblTicketPrice.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lblTicketPrice.setText("Ticket Price");
        jPanel2.add(lblTicketPrice);
        lblTicketPrice.setBounds(540, 430, 140, 30);

        btnGenerateTicket.setBackground(new java.awt.Color(215, 218, 227));
        btnGenerateTicket.setFont(new java.awt.Font("Georgia", 1, 25)); // NOI18N
        btnGenerateTicket.setText("GENERATE TICKET");
        btnGenerateTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateTicketMouseClicked(evt);
            }
        });
        btnGenerateTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTicketActionPerformed(evt);
            }
        });
        jPanel2.add(btnGenerateTicket);
        btnGenerateTicket.setBounds(20, 730, 290, 40);
        jPanel2.add(txtSeatno);
        txtSeatno.setBounds(710, 90, 190, 40);

        lblSeatNumber.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lblSeatNumber.setText("Seat Number");
        jPanel2.add(lblSeatNumber);
        lblSeatNumber.setBounds(530, 90, 160, 34);

        txtSourceDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSourceDestinationActionPerformed(evt);
            }
        });
        jPanel2.add(txtSourceDestination);
        txtSourceDestination.setBounds(260, 550, 200, 40);
        jPanel2.add(txtTicketprice);
        txtTicketprice.setBounds(710, 430, 190, 40);
        jPanel2.add(txtArrivalTime);
        txtArrivalTime.setBounds(710, 310, 190, 40);
        jPanel2.add(txtDeparture);
        txtDeparture.setBounds(710, 190, 190, 40);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 25)); // NOI18N
        jButton1.setText("PRINT ");
        jPanel2.add(jButton1);
        jButton1.setBounds(340, 730, 130, 40);

        jButton2.setFont(new java.awt.Font("Georgia", 1, 25)); // NOI18N
        jButton2.setText("RESET");
        jPanel2.add(jButton2);
        jButton2.setBounds(510, 730, 140, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(390, 140, 940, 850);

        txtArea.setBackground(new java.awt.Color(204, 255, 255));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(1340, 180, 560, 790);

        lblTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Frame.png"))); // NOI18N
        jPanel1.add(lblTrain);
        lblTrain.setBounds(60, 40, 260, 140);

        btnTrain.setBackground(new java.awt.Color(42, 134, 251));
        btnTrain.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnTrain.setForeground(new java.awt.Color(5, 51, 111));
        btnTrain.setText("TRAINS");
        btnTrain.setBorder(null);
        btnTrain.setBorderPainted(false);
        btnTrain.setContentAreaFilled(false);
        btnTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrainMouseExited(evt);
            }
        });
        btnTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrainActionPerformed(evt);
            }
        });
        jPanel1.add(btnTrain);
        btnTrain.setBounds(130, 460, 130, 60);

        lblBookings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tabler_brand-booking (1).png"))); // NOI18N
        jPanel1.add(lblBookings);
        lblBookings.setBounds(40, 620, 80, 80);

        btnBooking.setBackground(new java.awt.Color(42, 134, 251));
        btnBooking.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(5, 51, 100));
        btnBooking.setText("BOOKING");
        btnBooking.setBorder(null);
        btnBooking.setBorderPainted(false);
        btnBooking.setContentAreaFilled(false);
        btnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingMouseExited(evt);
            }
        });
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });
        jPanel1.add(btnBooking);
        btnBooking.setBounds(130, 630, 160, 60);

        lblTicekts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ticketsGreen.png"))); // NOI18N
        jPanel1.add(lblTicekts);
        lblTicekts.setBounds(45, 790, 80, 80);

        btnTicekts.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnTicekts.setForeground(new java.awt.Color(5, 51, 100));
        btnTicekts.setText("TICKETS");
        btnTicekts.setBorder(null);
        btnTicekts.setBorderPainted(false);
        btnTicekts.setContentAreaFilled(false);
        btnTicekts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTicektsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTicektsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTicektsMouseExited(evt);
            }
        });
        btnTicekts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicektsActionPerformed(evt);
            }
        });
        jPanel1.add(btnTicekts);
        btnTicekts.setBounds(140, 810, 140, 50);

        btnExit.setBackground(new java.awt.Color(42, 134, 251));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/material-symbols_logout-rounded.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(130, 960, 120, 90);

        lblTrains.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trainLabel.png"))); // NOI18N
        jPanel1.add(lblTrains);
        lblTrains.setBounds(40, 450, 80, 80);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/c.png"))); // NOI18N
        btnUser.setBorder(null);
        btnUser.setBorderPainted(false);
        btnUser.setContentAreaFilled(false);
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
        });
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnUser);
        btnUser.setBounds(130, 250, 130, 110);

        lblGreenBlueFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BlueGreen.png"))); // NOI18N
        jPanel1.add(lblGreenBlueFrame);
        lblGreenBlueFrame.setBounds(370, 0, 1554, 1130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1930, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTicektsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicektsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTicektsActionPerformed

    private void btnTicektsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicektsMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTicektsMouseExited

    private void btnTicektsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicektsMouseEntered
        // TODO add your handling code here:
         Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnTicekts.setCursor(cursor);
    }//GEN-LAST:event_btnTicektsMouseEntered

    private void btnTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainMouseClicked
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_btnTrainMouseClicked

    private void btnTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrainActionPerformed
        TrainButtonForm tbForm=new TrainButtonForm();
        tbForm.setVisible(true);     
        this.dispose();
        
    }//GEN-LAST:event_btnTrainActionPerformed

    private void btnTrainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainMouseEntered
        // TODO add your handling code here:
         Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnTrain.setCursor(cursor);
    }//GEN-LAST:event_btnTrainMouseEntered

    private void btnTrainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainMouseExited
        // TODO add your handling code here:
          btnTrain.setBackground(new java.awt.Color(42, 134, 251));
        btnTrain.setContentAreaFilled(false);
    }//GEN-LAST:event_btnTrainMouseExited

    private void btnBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseExited
        // TODO add your handling code here:
          btnBooking.setBackground(new java.awt.Color(42, 134, 251));
        btnBooking.setContentAreaFilled(false);
    }//GEN-LAST:event_btnBookingMouseExited

    private void btnBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseEntered
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnBooking.setCursor(cursor);
    }//GEN-LAST:event_btnBookingMouseEntered

    private void btnBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBookingMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        BookingButtonForm corm=new BookingButtonForm();
        corm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        dashboard db=new dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
         Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnUser.setCursor(cursor);
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
         Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnExit.setCursor(cursor);
    }//GEN-LAST:event_btnExitMouseEntered

    private void txtSourceDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSourceDestinationActionPerformed

    private void txpassengernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpassengernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpassengernameActionPerformed

    private void btnGenerateTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateTicketActionPerformed
        
       
        conn =MyConnection.dbConnect();
        
    
    try
        {
            stm=conn.createStatement();
            String sql="insert into tickets(ArrivalTime, departuretime, passengerid, passengername, phonenumber, seatnumber, sourcedestination, ticketprice, trainnumber)values('"+txtArrivalTime.getText()+"','"+txtDeparture.getText()+"','"+txtPassengerId.getText()+"','"+txpassengername.getText()+"','"+txtPhoneNumber.getText()+"','"+txtSeatno.getText()+"','"+txtSourceDestination.getText()+"','"+txtTicketprice.getText()+"','"+txtTrainno.getText()+"')";
              stm.executeUpdate(sql);
              System.out.println("data inserted");
              JOptionPane.showMessageDialog(this, "successfully registered", "teacher", JOptionPane.INFORMATION_MESSAGE);
              
        }
        catch(Exception e){
            System.out.println(e.getMessage());
                    
        
        }
        
    
    
//    txtArea.setText("*************************************\n");
//    txtArea.setText(txtArea.getText()+"**\n");
    
    Date obj=new Date();
    String date=obj.toString();
    txtArea.setText("                              TICKET                                        \n\n");
    txtArea.setText(txtArea.getText()+"\n"+date+"\n\n\n");
    txtArea.setText(txtArea.getText()+"Departure Time:  "+txtDeparture.getText());
    txtArea.setText(txtArea.getText()+"                   Arrival Time:  "+txtArrivalTime.getText()+"\n\n\n");
   
    txtArea.setText(txtArea.getText()+"Passenger Name:  "+txpassengername.getText()+"\n");
    txtArea.setText(txtArea.getText()+"Train Number:  "+txtTrainno.getText()+"\n");
    txtArea.setText(txtArea.getText()+"To The Destination:  "+txtSourceDestination.getText()+"\n");
    txtArea.setText(txtArea.getText()+"Your Seat Number is:  "+txtSeatno.getText()+"\n");
    txtArea.setText(txtArea.getText()+"Ticket Price:  "+txtTicketprice.getText()+"\n");
    
    
    
    
    
   

    }//GEN-LAST:event_btnGenerateTicketActionPerformed

    private void btnTicektsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicektsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTicektsMouseClicked

    private void btnGenerateTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateTicketMouseClicked
        
    }//GEN-LAST:event_btnGenerateTicketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketButtonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerateTicket;
    private javax.swing.JButton btnTicekts;
    private javax.swing.JButton btnTrain;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArrivalTime;
    private javax.swing.JLabel lblBookings;
    private javax.swing.JLabel lblDepartureTime;
    private javax.swing.JLabel lblGreenBlueFrame;
    private javax.swing.JLabel lblPassengerId;
    private javax.swing.JLabel lblPassengerName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSeatNumber;
    private javax.swing.JLabel lblSourceDestination;
    private javax.swing.JLabel lblTicekts;
    private javax.swing.JLabel lblTicketPrice;
    private javax.swing.JLabel lblTrain;
    private javax.swing.JLabel lblTrainNumber;
    private javax.swing.JLabel lblTrains;
    private javax.swing.JTextField txpassengername;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtArrivalTime;
    private javax.swing.JTextField txtDeparture;
    private javax.swing.JTextField txtPassengerId;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSeatno;
    private javax.swing.JTextField txtSourceDestination;
    private javax.swing.JTextField txtTicketprice;
    private javax.swing.JTextField txtTrainno;
    // End of variables declaration//GEN-END:variables
}
