/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author saroj
 */


import controller.reportController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.reportModel;
import java.awt.Cursor;
import javax.swing.JScrollPane;
import javax.swing.JTable;

public class report extends javax.swing.JFrame {
    private DefaultTableModel model;
    private JTable table;
   
 public void updateTable() {
        // Refresh the table view
        table.setModel(model);
        table.repaint();
    }

 
    public report() {
        initComponents();
        model = new DefaultTableModel();
        table = new JTable(model);
        
         btn_custom.setVisible(false);
    btn_printImg.setVisible(false);

        // Add the table to a scroll pane
        JScrollPane scrollPane = new JScrollPane(table);
        
    }

    /**
     * Creates new form report
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablereport = new javax.swing.JTable();
        btn_printImg = new javax.swing.JButton();
        btn_printexcel = new javax.swing.JButton();
        btn_printpdf = new javax.swing.JButton();
        btn_custom = new javax.swing.JButton();
        btn_thisweek = new javax.swing.JButton();
        btn_thismonth = new javax.swing.JButton();
        btn_thisyear = new javax.swing.JButton();
        btn_today = new javax.swing.JButton();
        lbl_transaction = new javax.swing.JLabel();
        report_frame = new javax.swing.JLabel();
        dashrectangleimg = new javax.swing.JLabel();
        trackhubLabel = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        btnTrain = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        lblTrain = new javax.swing.JLabel();
        lblBooking = new javax.swing.JLabel();
        lblTickets = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        tablereport.setFont(new java.awt.Font("Georgia", 0, 30)); // NOI18N
        tablereport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null, null},
                {null, "", null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Passenger Number", "No. of TIckets", "Class", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablereport.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablereport.setGridColor(new java.awt.Color(255, 255, 255));
        tablereport.setRowHeight(50);
        tablereport.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tablereport.setShowGrid(true);
        jScrollPane1.setViewportView(tablereport);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(550, 352, 1160, 550);

        btn_printImg.setBackground(new java.awt.Color(5, 51, 111));
        btn_printImg.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        btn_printImg.setForeground(new java.awt.Color(255, 255, 255));
        btn_printImg.setText("Print as Image");
        btn_printImg.setBorder(null);
        btn_printImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btn_printImg);
        btn_printImg.setBounds(1416, 930, 259, 54);

        btn_printexcel.setBackground(new java.awt.Color(5, 51, 111));
        btn_printexcel.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        btn_printexcel.setForeground(new java.awt.Color(255, 255, 255));
        btn_printexcel.setText("Print as Excel");
        btn_printexcel.setBorder(null);
        btn_printexcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_printexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printexcelActionPerformed(evt);
            }
        });
        jPanel2.add(btn_printexcel);
        btn_printexcel.setBounds(1039, 930, 259, 54);

        btn_printpdf.setBackground(new java.awt.Color(5, 51, 111));
        btn_printpdf.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        btn_printpdf.setForeground(new java.awt.Color(255, 255, 255));
        btn_printpdf.setText("Print as PDF");
        btn_printpdf.setBorder(null);
        btn_printpdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_printpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printpdfActionPerformed(evt);
            }
        });
        jPanel2.add(btn_printpdf);
        btn_printpdf.setBounds(662, 930, 259, 54);

        btn_custom.setBackground(new java.awt.Color(5, 51, 111));
        btn_custom.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        btn_custom.setForeground(new java.awt.Color(255, 255, 255));
        btn_custom.setText("Custom");
        btn_custom.setBorder(null);
        btn_custom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btn_custom);
        btn_custom.setBounds(1535, 270, 180, 54);

        btn_thisweek.setBackground(new java.awt.Color(5, 51, 111));
        btn_thisweek.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        btn_thisweek.setForeground(new java.awt.Color(255, 255, 255));
        btn_thisweek.setText("This Week");
        btn_thisweek.setBorder(null);
        btn_thisweek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_thisweek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thisweekActionPerformed(evt);
            }
        });
        jPanel2.add(btn_thisweek);
        btn_thisweek.setBounds(803, 270, 180, 54);

        btn_thismonth.setBackground(new java.awt.Color(5, 51, 111));
        btn_thismonth.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        btn_thismonth.setForeground(new java.awt.Color(255, 255, 255));
        btn_thismonth.setText("This Month");
        btn_thismonth.setBorder(null);
        btn_thismonth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_thismonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thismonthActionPerformed(evt);
            }
        });
        jPanel2.add(btn_thismonth);
        btn_thismonth.setBounds(1053, 270, 180, 54);

        btn_thisyear.setBackground(new java.awt.Color(5, 51, 111));
        btn_thisyear.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        btn_thisyear.setForeground(new java.awt.Color(255, 255, 255));
        btn_thisyear.setText("This Year");
        btn_thisyear.setBorder(null);
        btn_thisyear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_thisyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thisyearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_thisyear);
        btn_thisyear.setBounds(1303, 270, 180, 54);

        btn_today.setBackground(new java.awt.Color(5, 51, 111));
        btn_today.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        btn_today.setForeground(new java.awt.Color(255, 255, 255));
        btn_today.setText("Today");
        btn_today.setBorder(null);
        btn_today.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todayActionPerformed(evt);
            }
        });
        jPanel2.add(btn_today);
        btn_today.setBounds(553, 271, 180, 54);

        lbl_transaction.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        lbl_transaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_transaction.setText("Transaction History");
        jPanel2.add(lbl_transaction);
        lbl_transaction.setBounds(921, 164, 443, 58);

        report_frame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        report_frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report_frame.png"))); // NOI18N
        jPanel2.add(report_frame);
        report_frame.setBounds(485, 111, 1316, 890);

        dashrectangleimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashrectangleimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BlueGreen.png"))); // NOI18N
        dashrectangleimg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(dashrectangleimg);
        dashrectangleimg.setBounds(366, 0, 1554, 1080);

        trackhubLabel.setBackground(new java.awt.Color(255, 51, 51));
        trackhubLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trackhubLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Frame.png"))); // NOI18N
        jPanel2.add(trackhubLabel);
        trackhubLabel.setBounds(60, 40, 260, 160);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userGreen.png"))); // NOI18N
        btnUser.setBorder(null);
        btnUser.setBorderPainted(false);
        btnUser.setContentAreaFilled(false);
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
        });
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnUser);
        btnUser.setBounds(100, 240, 160, 120);

        btnTrain.setBackground(new java.awt.Color(42, 134, 251));
        btnTrain.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnTrain.setForeground(new java.awt.Color(5, 51, 111));
        btnTrain.setText("TRAINS");
        btnTrain.setBorder(null);
        btnTrain.setBorderPainted(false);
        btnTrain.setContentAreaFilled(false);
        btnTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrainMouseExited(evt);
            }
        });
        btnTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrainActionPerformed(evt);
            }
        });
        jPanel2.add(btnTrain);
        btnTrain.setBounds(130, 450, 150, 60);

        btnBooking.setBackground(new java.awt.Color(42, 134, 251));
        btnBooking.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(5, 51, 111));
        btnBooking.setText("BOOKING");
        btnBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(42, 134, 251)));
        btnBooking.setBorderPainted(false);
        btnBooking.setContentAreaFilled(false);
        btnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingMouseExited(evt);
            }
        });
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });
        jPanel2.add(btnBooking);
        btnBooking.setBounds(140, 620, 150, 60);

        btnTickets.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnTickets.setForeground(new java.awt.Color(5, 51, 111));
        btnTickets.setText("TICKETS");
        btnTickets.setBorder(null);
        btnTickets.setBorderPainted(false);
        btnTickets.setContentAreaFilled(false);
        btnTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTicketsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTicketsMouseExited(evt);
            }
        });
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });
        jPanel2.add(btnTickets);
        btnTickets.setBounds(140, 790, 140, 60);

        lblTrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trainLabel.png"))); // NOI18N
        jPanel2.add(lblTrain);
        lblTrain.setBounds(40, 440, 80, 80);

        lblBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabler_brand-booking (1).png"))); // NOI18N
        jPanel2.add(lblBooking);
        lblBooking.setBounds(40, 610, 80, 80);

        lblTickets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashicons_tickets-alt.png"))); // NOI18N
        jPanel2.add(lblTickets);
        lblTickets.setBounds(40, 780, 70, 70);

        btnExit.setBackground(new java.awt.Color(42, 134, 251));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit);
        btnExit.setBounds(110, 930, 160, 90);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1920, 1080);

        setBounds(0, 0, 1936, 1088);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnUser.setCursor(cursor);
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed

    }//GEN-LAST:event_btnUserActionPerformed

    private void btnTrainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainMouseEntered
        // TODO add your handling code here:

        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnTrain.setCursor(cursor);

    }//GEN-LAST:event_btnTrainMouseEntered

    private void btnTrainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainMouseExited
        // TODO add your handling code here:
        btnTrain.setBackground(new java.awt.Color(42, 134, 251));
        btnTrain.setContentAreaFilled(false);

    }//GEN-LAST:event_btnTrainMouseExited

    private void btnTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrainActionPerformed
        // TODO add your handling code here:
        TrainButtonForm train=new TrainButtonForm();
        train.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnTrainActionPerformed

    private void btnBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseEntered
        // TODO add your handling code here:
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnBooking.setCursor(cursor);

    }//GEN-LAST:event_btnBookingMouseEntered

    private void btnBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseExited
        // TODO add your handling code here:

        btnBooking.setBackground(new java.awt.Color(42, 134, 251));
        btnBooking.setContentAreaFilled(false);
    }//GEN-LAST:event_btnBookingMouseExited

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        BookingButtonForm b=new BookingButtonForm();
        b.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnTicketsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketsMouseEntered
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnTickets.setCursor(cursor);
    }//GEN-LAST:event_btnTicketsMouseEntered

    private void btnTicketsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketsMouseExited
        btnTickets.setBackground(new java.awt.Color(42, 134, 251));
        btnTickets.setContentAreaFilled(false);
    }//GEN-LAST:event_btnTicketsMouseExited

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
        // TODO add your handling code here:
        TicketButtonForm ob=new TicketButtonForm();
        ob.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnTicketsActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        btnExit.setCursor(cursor);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        login s= new login();
        s.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btn_todayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todayActionPerformed
        // TODO add your handling code here:
       String selectedButton = "today";
        DefaultTableModel model = (DefaultTableModel) tablereport.getModel();
        reportController controller = new reportController();
        controller.populateTable(model, selectedButton);

        
        
    }//GEN-LAST:event_btn_todayActionPerformed

    private void btn_thisweekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thisweekActionPerformed
        // TODO add your handling code here
                 String selectedButton = "thisweek";
        DefaultTableModel model = (DefaultTableModel) tablereport.getModel();
        reportController controller = new reportController();
        controller.populateTable(model, selectedButton);
    }//GEN-LAST:event_btn_thisweekActionPerformed

    private void btn_thismonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thismonthActionPerformed
         String selectedButton = "thismonth";
        DefaultTableModel model = (DefaultTableModel) tablereport.getModel();
        reportController controller = new reportController();
        controller.populateTable(model, selectedButton);
    }//GEN-LAST:event_btn_thismonthActionPerformed

    private void btn_thisyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thisyearActionPerformed
        // TODO add your handling code here:
         String selectedButton = "thisyear";
        DefaultTableModel model = (DefaultTableModel) tablereport.getModel();
        reportController controller = new reportController();
        controller.populateTable(model, selectedButton);
    }//GEN-LAST:event_btn_thisyearActionPerformed

    private void btn_printpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printpdfActionPerformed
        // TODO add your handling code here:
        reportController controller = new reportController();
        //controller.saveAsPDF((model) jTable1.getModel());
        controller.saveAsPDF((DefaultTableModel) tablereport.getModel());
    }//GEN-LAST:event_btn_printpdfActionPerformed

    private void btn_printexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printexcelActionPerformed
        // TODO add your handling code here:
        reportController controller = new reportController();
        //controller.saveAsPDF((model) jTable1.getModel());
        controller.saveAsExcel((DefaultTableModel) tablereport.getModel());
    }//GEN-LAST:event_btn_printexcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTickets;
    private javax.swing.JButton btnTrain;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton btn_custom;
    private javax.swing.JButton btn_printImg;
    private javax.swing.JButton btn_printexcel;
    private javax.swing.JButton btn_printpdf;
    private javax.swing.JButton btn_thismonth;
    private javax.swing.JButton btn_thisweek;
    private javax.swing.JButton btn_thisyear;
    private javax.swing.JButton btn_today;
    private javax.swing.JLabel dashrectangleimg;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBooking;
    private javax.swing.JLabel lblTickets;
    private javax.swing.JLabel lblTrain;
    private javax.swing.JLabel lbl_transaction;
    private javax.swing.JLabel report_frame;
    private javax.swing.JTable tablereport;
    private javax.swing.JLabel trackhubLabel;
    // End of variables declaration//GEN-END:variables
}
